Escola/Controllers/CadastroController.cs
using Dados;
using Dados.DAO;
using Dados.Entities;
using Escola.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Escola.Controllers
{
    public class CadastroController : Controller
    {
        #region Cadastro Usuario
        public ActionResult Usuario()
        {
           
            return View();
        }
            
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarUsuario(int id)
        {
            return Json(UsuarioModel.recuperarPeloId(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            var resultado = "OK";
            var mensagems = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagems = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    
                    var id = model.salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception)
                {

                    resultado = "ERRO";
                }

            }
            return Json(new { Resultado = resultado, Mensagems = mensagems, IdSalvo = idSalvo });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuario(int id)
        {
            return Json(UsuarioModel.excluirPeloId(id));
        }
        #endregion


        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }

        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }

        [Authorize]
        public ActionResult Bairro()
        {
            return View();
        }

        [Authorize]
        public ActionResult EnderecoAluno()
        {
            return View();
        }

        [Authorize]
        public ActionResult PaiAluno()
        {
            return View();
        }

        [Authorize]
        public ActionResult MaeAluno()
        {
            return View();
        }

        [Authorize]
        public ActionResult Aluno()
        {
            return View();
        }
    }
}

Escola/Views/Cadastro/Usuario.cshtml
@model Escola.Models.UsuarioModel
@{
    ViewBag.Title = "Cadastro de Usuarios";
}
@Html.Hidden("id_cadastro")
<div class="form_cadastro">
    
        <div id="msg_mensagem_aviso" class="text-danger invisivel"></div>
        <!-- DADOS PESSOAIS-->
        <fieldset>
            @Html.AntiForgeryToken()
            <legend>Dados Pessoais</legend>
            <table cellspacing="10">
                <tr>
                    <td>
                        @Html.Label("txt_nome", "Nome", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.TextBox("txt_nome", null, new { @class = "input-text", type = "text" })
                    </td>
                    <td>
                        @Html.Label("ddl_sexo", "Sexo", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.DropDownList("ddl_sexo",(SelectList)ViewBag.DropSexoValues, new {@class="appearance-select" })
                    </td>
                    <td>
                        @Html.Label("ddl_cidade", "Cidade", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.DropDownList("ddl_cidade", (SelectList)ViewBag.CidadeId , new {@class="appearance-select" })
                    </td>
                </tr>
                <tr>
                    
                    <td>
                        @Html.Label("txt_cpf", "Cpf", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.TextBox("txt_cpf", null, new { @class = "input-text", type = "text" })
                    </td>

                    <td>
                        @Html.Label("txt_telefone", "Telefone", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.TextBox("txt_telefone", null, new { @class = "input-text", type = "text" })
                    </td>
                </tr>
            </table>
        </fieldset>

        <br />

        <!-- DADOS DE LOGIN -->
        <fieldset>
            @Html.AntiForgeryToken()
            <legend>Dados de login</legend>
            <table cellspacing="10">
                <tr>
                    <td>
                        @Html.Label("txt_email", "Email", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.TextBox("txt_email", null, new { @class = "input-text", type = "email" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("txt_pass", "Password", new { @class = "" })
                    </td>
                    <td align="left">
                        @Html.TextBox("txt_pass", null, new { @class = "input-text", type = "password" })
                    </td>
                </tr>
             
            </table>
        </fieldset>
        <br />
        <div><input type="submit" role="button" class="button2" value="Cadastrar"></div>

    </div>


@section Scripts{
    <script>

        function add_anti_forgery_token(data) {
            data.__RequestVerificationToken = $('[name=__RequestVerificationToken]').val();
            return data;
        }

        function abrirForm(dados) {
            $('#id_cadastro').val(dados.Codigo);
            $('#txt_nome').val(dados.Nome);
            $('#txt_nome').val(dados.Cpf);
            $('#txt_nome').val(dados.Sexo);
            $('#txt_nome').val(dados.Telefone);
            $('#txt_nome').val(dados.Cidade_id);
            $('#txt_nome').val(dados.Email);
            $('#txt_senha').val(dados.Senha);

        }

        $(document).on('click', '#submit', function () {
            var btn = $(this),
                url = '@Url.Action("SalvarUsuario","Cadastro")',
                param = {
                    Codigo: $('#id_cadastro').val(),
                    Nome: $('#txt_nome').val(),
                    Cpf: $('#txt_login').val(),
                    Sexo: $('#txt_senha').val(),
                    Telefone: $('#txt_senha').val(),
                    Cidade_id: $('#txt_senha').val(),
                    Email: $('#txt_senha').val(),
                    Senha: $('#txt_senha').val()
                };
        });
    </script>
}